### ISSUE TITLE
Issue on code blocks

### ISSUE THREAD

**Issue by Fastidious** [h16nning/typora-gitbook-theme#28]
Typora latest update has broken the code blocks (tested under macOS). See (line six):

<img width="809" alt="Screenshot 2021-07-23 at 08 51 07" src="https://user-images.githubusercontent.com/8352292/126786722-fa62b0c8-0558-40e0-9523-a1d7d036dac2.png">

**Comment by h16nning** [comment]
This issue only occurs when scroll bars are always enabled in the macOS preferences.

**Comment by h16nning** [comment]
Hi @Fastidious, the issue should be fixed in version 1.10.4.
