### ISSUE TITLE
In the code block, the line number is displayed incorrectly

### ISSUE THREAD

**Issue by chexunn** [h16nning/typora-gitbook-theme#34]
In the code block, it seems that the line number can only display two digits. When the line number exceeds 99, an exception is displayed.

As shown below:

![image](https://user-images.githubusercontent.com/18463575/138041444-ee705f97-55cf-4078-b826-2b8344d9cd08.png)

This problem is both on macOS and Windows.

**Comment by h16nning** [comment]
Hey @chexunn,
the issue should be fixed in [the latest release](https://www.github.com/h16nning/typora-gitbook-theme/releases/latest).
