### ISSUE TITLE
Reduce left padding in code block

### ISSUE THREAD

**Issue by pencilheart** [h16nning/typora-gitbook-theme#49]
Hi, thanks for your theme, it's really beautiful. 
I'm a mac user, I'd like none padding in code block, like default theme `GitHub`. However, I have set `padding` to `0rem`, but it's also different with `GitHub`theme. Is there any way to further reduce the left padding in the code block to be like `Github` theme?
https://github.com/h16nning/typora-gitbook-theme/blob/d57b82455463fcdf97937dd1e05eb31a28ae86ac/src/gitbook-azure.css#L499-L504
1. This `Gitbook-Azure` theme(`padding=1rem`):
    <img width="852" alt="image" src="https://user-images.githubusercontent.com/61617063/218295768-4491cdee-3447-4008-92f2-36851eced369.png">
1. This `Gitbook-Azure` theme(`padding=0rem`):
    <img width="857" alt="image" src="https://user-images.githubusercontent.com/61617063/218295329-cdd77d01-7399-4c28-a365-fb353fc66140.png">
1. Default `Github` theme:
    <img width="805" alt="image" src="https://user-images.githubusercontent.com/61617063/218295315-55e5e3f7-fa1b-47a7-8321-95c85ca71195.png">

**Comment by h16nning** [comment]
Hi @pencilheart,
I'm glad you like my theme. Try reducing the top and bottom padding in the inner code mirror box by adding this to the css file:

`.CodeMirror.cm-s-inner {
    padding-top: 0px;
    padding-bottom: 0px;
}`

You can change the value to something you like as 0px could be a little low. Normally this should be around 16px. I hope this helps!

**Comment by pencilheart** [comment]
Thanks @h16nning.

Oh, I have done this, but there's no change, it can only increase the top and bottom padding if the `padding-top` and `padding-bottom` are more than `0px`. Also, I use `.CodeMirror.cm-s-inner { padding-top: 0px; padding-bottom: 0px; padding-left: 0px;}` but still fail.

I see there should be code line number, but in mac there's none. Or canceling code line number can help? How to do that?

**Comment by pencilheart** [comment]
I just learned how to using `Help -> Enable Debug` to custom CSS. Finally, Line 684 did work!

https://github.com/h16nning/typora-gitbook-theme/blob/d57b82455463fcdf97937dd1e05eb31a28ae86ac/src/gitbook-azure.css#L680-L686

Here is `padding=0.5rem`:

<img width="853" alt="image" src="https://user-images.githubusercontent.com/61617063/218335630-bc2a7647-bdc7-4054-aa51-d6dd1662ca72.png">

Thanks for your nice theme again 💯
